joy_teleop:
  ros__parameters:
    piloting:
      type: topic
      interface_type: "geometry_msgs/msg/Twist"
      topic_name: cmd_vel
      deadman_buttons: [4]
      axis_mappings:
        linear-x:
          axis: 1  # Right thumb (up/down)
          scale: 0.4
          offset: 0.0
        angular-z:
          axis: 2  # Right thumb stick (left/right)
          scale: 2.5
          offset: 0.0
